name: CI

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Setup Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      - name: Code Quality
        run: |
          poetry run black . --check

      - name: Test with pytest
        env:
          SERIATION_LOG_FORMAT: COLOR
          SERIATION_LOG_LEVEL: 50
        run: |
          poetry run pytest -s -vvv